#!/usr/bin/env python3
"""
Helper script to copy SmolVLM2 architecture code from transformers library.

This script extracts the architecture code from transformers and creates
a standalone version that can be used without transformers at runtime.

Usage:
    python tools/convert_weights/copy_smolvlm_architecture.py \
        --output nets/smolvlm2/architecture_smolvlm2.py
"""

import argparse
import os
import sys
import inspect
import importlib.util

def find_transformers_smolvlm_module():
    """Find the SmolVLM modeling module in transformers"""
    try:
        from transformers.models.smolvlm import modeling_smolvlm
        return modeling_smolvlm
    except ImportError:
        # Try to find it manually
        import transformers
        transformers_path = os.path.dirname(inspect.getfile(transformers))
        smolvlm_path = os.path.join(
            transformers_path,
            "models", "smolvlm", "modeling_smolvlm.py"
        )
        if os.path.exists(smolvlm_path):
            spec = importlib.util.spec_from_file_location(
                "modeling_smolvlm", smolvlm_path
            )
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            return module
        else:
            raise FileNotFoundError(
                f"Could not find SmolVLM modeling file at {smolvlm_path}"
            )


def extract_architecture_code(module, output_path: str):
    """Extract and adapt architecture code from transformers module"""
    
    # Read the source file
    source_file = inspect.getfile(module)
    with open(source_file, 'r', encoding='utf-8') as f:
        source_code = f.read()
    
    # Create adapted version
    # Replace transformers imports with local imports
    adapted_code = source_code
    
    # Add header
    header = '''"""
SmolVLM2 Architecture Implementation

This file contains the architecture code copied from transformers library.
This allows loading from state_dict without requiring transformers at runtime.

Source: transformers/models/smolvlm/modeling_smolvlm.py
Generated by: tools/convert_weights/copy_smolvlm_architecture.py

NOTE: This file may need manual adjustments for:
- Import paths (transformers -> local equivalents)
- Dependencies that are not available locally
- Version compatibility
"""

'''
    
    # Write to output
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header)
        f.write(adapted_code)
    
    print(f"✓ Architecture code copied to {output_path}")
    print(f"  Source: {source_file}")
    print(f"  ⚠️  NOTE: You may need to manually adjust imports and dependencies")


def main():
    parser = argparse.ArgumentParser(
        description="Copy SmolVLM2 architecture code from transformers"
    )
    parser.add_argument(
        "--output",
        type=str,
        default="nets/smolvlm2/architecture_smolvlm2.py",
        help="Output path for architecture code"
    )
    
    args = parser.parse_args()
    
    # Resolve absolute path
    if not os.path.isabs(args.output):
        project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        args.output = os.path.join(project_root, args.output)
    
    print("Finding SmolVLM architecture in transformers...")
    try:
        module = find_transformers_smolvlm_module()
        print(f"✓ Found module: {inspect.getfile(module)}")
        
        print("Extracting architecture code...")
        extract_architecture_code(module, args.output)
        
        print("\n✓ Done!")
        print("\nNext steps:")
        print("1. Review the generated file and fix any import issues")
        print("2. Test loading a checkpoint with state_dict format")
        print("3. Update imports in architecture_smolvlm2.py if needed")
        
    except Exception as e:
        print(f"✗ Error: {e}")
        print("\nManual steps:")
        print("1. Find transformers/models/smolvlm/modeling_smolvlm.py")
        print("2. Copy relevant classes (SmolVLMModel, etc.)")
        print("3. Adjust imports to work without transformers")
        print("4. Save to nets/smolvlm2/architecture_smolvlm2.py")
        sys.exit(1)


if __name__ == "__main__":
    main()



